/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.import_excel;

import java.awt.print.PrinterException;
import java.util.List;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author jerbi
 */
public class excel extends javax.swing.JFrame {

    private File excel;

    /**
     * Creates new form excel
     */
    public excel() throws ClassNotFoundException {
        initComponents();
        load_table_bd();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @throws java.lang.ClassNotFoundException
     */
     public void load_table_bd() throws ClassNotFoundException{
        String url = "jdbc:mysql://localhost:3306/bd_excel";
        String username = "root";
        String passw="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection(url,username,passw)) {
                Statement st = conn.createStatement();
                String req = "SELECT * FROM test;";
                ResultSet rt = st.executeQuery(req);
                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("id");
                tb.addColumn("nom");
                tb.addColumn("numero");
                while(rt.next()){
                    tb.addRow(new Object[]{rt.getString(1),rt.getString(2),rt.getString(3)});
                }
                jTable3.setModel(tb);
                
            }
            
        }
        catch(SQLException e ){
            JOptionPane.showMessageDialog(null, "erreur "+e.getMessage(), "ERREUR!", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }
    public void sauvegarder_excel(File excel){
        try {
            Workbook workbook = new XSSFWorkbook(new FileInputStream(excel));
            Sheet sheet = workbook.getSheetAt(0);
            while (sheet.getLastRowNum() > 0) {
                    sheet.removeRow(sheet.getRow(sheet.getLastRowNum()));
                }
           try{
               DefaultTableModel tb = new DefaultTableModel();
               tb=(DefaultTableModel) jTable2.getModel();
               for(int j =0;j<tb.getRowCount();j++){
                    Row new_row=sheet.createRow(j);
                    for(int k=0;k<tb.getColumnCount();k++){
                        Cell new_cel=new_row.createCell(k);
                        new_cel.setCellValue(tb.getValueAt(j,k).toString());
                            
                    }
                }
                try (FileOutputStream fileOut = new FileOutputStream(excel.getAbsolutePath())) {
                    workbook.write(fileOut);
                        
                }catch (IOException e) {
                    e.printStackTrace();
                }

           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, "erreur "+e.getMessage(), "ERREUR!", JOptionPane.WARNING_MESSAGE);
           }
        } catch (IOException ex) {
            Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Traiter un fichier excel");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("importer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("nom");

        jLabel4.setText("numero");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nom", "Numero"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getAccessibleContext().setAccessibleName("tab");

        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Numero"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable3MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Imprimer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Ajouter");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Les données de la  base de données");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4))
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton4)
                                .addGap(48, 48, 48)
                                .addComponent(jButton5)
                                .addGap(58, 58, 58)
                                .addComponent(jButton7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton9)
                        .addGap(48, 48, 48)
                        .addComponent(jButton10)
                        .addGap(58, 58, 58)
                        .addComponent(jButton11)))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(837, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(236, 236, 236)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton8)
                            .addComponent(jButton6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel6)
                    .addContainerGap(610, Short.MAX_VALUE)))
        );

        jTextField1.getAccessibleContext().setAccessibleName("path_file");
        jButton3.getAccessibleContext().setAccessibleName("44");
        jTextField2.getAccessibleContext().setAccessibleName("id");
        jTextField3.getAccessibleContext().setAccessibleName("nom");
        jTextField4.getAccessibleContext().setAccessibleName("num");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        fc.setDialogTitle("Selectionner un fichier excel");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        fc.setFileFilter(fnef);
        excel = fc.getSelectedFile();
        jTextField1.setText(excel.getAbsolutePath());
        try{
            Workbook workbook = new XSSFWorkbook(new FileInputStream(excel));
            Sheet sheet = workbook.getSheetAt(0);
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("id");
            tb.addColumn("nom");
            tb.addColumn("numero");
            for(Row row : sheet){
                List<String> liste = new ArrayList<>();
                for(Cell cell : row){
                        liste.add(cell.getStringCellValue());
                }
                tb.addRow(liste.toArray());
            }
            jTable2.setModel(tb);
        }
        catch(IOException e ){
            System.out.println("erreur "+e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        if(i>-1){
            jTextField2.setText((String) jTable2.getValueAt(i,0));
            jTextField3.setText((String) jTable2.getValueAt(i,1));
            jTextField4.setText((String) jTable2.getValueAt(i,2));
            
        }
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/bd_excel";
        String username = "root";
        String passw="";
        int [] tab = jTable2.getSelectedRows();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url,username,passw);
            int choix = JOptionPane.showOptionDialog(
                null,
                "Vous voulez supprimez les données de la base et les remplacer par les données du sheet ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Oui", "Non"},
                "Oui"
            );
            if(choix==JOptionPane.YES_OPTION){
                String req_del="DELETE FROM test;";
                Statement stmt = conn.createStatement();
                stmt.executeUpdate(req_del);
                DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
                
                for(int i =0 ; i<tb.getRowCount();i++){
                    String requete  = "INSERT INTO `test` (`ID`, `nom`, `numero`) VALUES (?, ?, ?);";
                    try(PreparedStatement ps= conn.prepareStatement(requete)){
                        ps.setString(1, tb.getValueAt(i, 0).toString());
                        ps.setString(2, tb.getValueAt(i, 1).toString());
                        ps.setString(3, tb.getValueAt(i, 2).toString());
                        ps.executeUpdate();
                    }
                }
                
            }
            else if(choix==JOptionPane.NO_OPTION){
                DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
                 for(int i =0 ; i<tab.length;i++){
                    String requete  = "INSERT INTO `test` (`ID`, `nom`, `numero`) VALUES (?, ?, ?);";
                    try(PreparedStatement ps= conn.prepareStatement(requete)){
                        ps.setString(1, tb.getValueAt(tab[i], 0).toString());
                        ps.setString(2, tb.getValueAt(tab[i], 1).toString());
                        ps.setString(3, tb.getValueAt(tab[i], 2).toString());
                        ps.executeUpdate();
                    }
                }
                
            }
            
            
        }
        catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Pilote JDBC introuvable.", "ERREUR!", JOptionPane.WARNING_MESSAGE);
        }
        catch(SQLException e ){
            JOptionPane.showMessageDialog(null, "erreur "+e.getMessage(), "ERREUR!", JOptionPane.WARNING_MESSAGE);
        }
        try {
            load_table_bd();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = new DefaultTableModel();
        tb = (DefaultTableModel) jTable2.getModel();
        String rech_id = jTextField1.getText().toString();
        int i=0 ;
        if(rech_id.isEmpty()==false){
            for(i =0; i<tb.getRowCount();i++){
               String id = tb.getValueAt(i, 0).toString();
               System.out.println(tb.getValueAt(i, 0).toString());
               if(rech_id.compareTo(id)==0){
                   jTextField2.setText((String) jTable2.getValueAt(i,0));
                   jTextField3.setText((String) jTable2.getValueAt(i,1));
                   jTextField4.setText((String) jTable2.getValueAt(i,2));
                   break;
               }
               
            }
            if(i==tb.getRowCount()){
                 
                JOptionPane.showMessageDialog(null, "On n'a pas pu trouver l'id saisi", "INTROUVABLE!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Veuillez remplir le textfield.", "ERREUR!", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().toString().isEmpty()==false && jTextField4.getText().toString().isEmpty()==false && jTextField3.getText().toString().isEmpty()==false ){
            DefaultTableModel tb1 = new DefaultTableModel();
            tb1=(DefaultTableModel) jTable2.getModel();
            tb1.addRow(new Object[]{jTextField2.getText().toString(),jTextField3.getText().toString(),jTextField4.getText().toString()});
            
            jTable2.setModel(tb1);
            sauvegarder_excel(excel);
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Veuillez remplir le textfield.", "ERREUR!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        DefaultTableModel tb2 = (DefaultTableModel) jTable2.getModel(); // Récupérer le modèle existant de la JTable

        if (i > -1) {
            tb2.removeRow(i);
            JOptionPane.showMessageDialog(null, "Ligne bien supprimée", "Bravo!", JOptionPane.INFORMATION_MESSAGE);
            jTable2.setModel(tb2);
            sauvegarder_excel(excel);
            i = -1;
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MousePressed
        // TODO add your handling code here:
        int i = jTable3.getSelectedRow();
        if(i>-1){
            jTextField2.setText((String) jTable3.getValueAt(i,0));
            jTextField3.setText((String) jTable3.getValueAt(i,1));
            jTextField4.setText((String) jTable3.getValueAt(i,2));
            
        }
    }//GEN-LAST:event_jTable3MousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String id = jTextField2.getText();
        String nom = jTextField3.getText();
        String num = jTextField4.getText();
        int i = jTable2.getSelectedRow();
        DefaultTableModel tb = new DefaultTableModel();
        tb=(DefaultTableModel) jTable2.getModel();
        if(i>-1){
            tb.setValueAt(id, i, 0);
            tb.setValueAt(nom, i, 1);
            tb.setValueAt(num, i, 2);
            jTable2.setModel(tb);
            sauvegarder_excel(excel);
            JOptionPane.showMessageDialog(null, "Ligne bien modifiée", "Bravo!", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        try{
            MessageFormat header = new MessageFormat("La liste des clients\n");
            MessageFormat footer = new MessageFormat("Page{0,number, integer}");
            jTable3.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        }
        catch(PrinterException e){
            JOptionPane.showMessageDialog(null, "erreur d'impression"+e.getMessage(), "ERREUR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/bd_excel";
        String username = "root";
        String passw="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url, username, passw);
            String req = "INSERT INTO `test` (`ID`, `nom`, `numero`) VALUES (?, ?,?);";
            try(PreparedStatement ps = conn.prepareStatement(req) ){
                ps.setString(1, jTextField2.getText().toString());
                ps.setString(2, jTextField3.getText().toString());
                ps.setString(3, jTextField4.getText().toString());
                ps.executeUpdate();
                DefaultTableModel tb = new DefaultTableModel();
                tb = (DefaultTableModel) jTable3.getModel();
                tb.addRow(new Object[]{jTextField2.getText().toString(),jTextField3.getText().toString(),jTextField4.getText().toString()});
                jTable3.setModel(tb);
                
            } catch (SQLException ex) {
                Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/bd_excel";
        String username = "root";
        String passw="";
        int ligne = 0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url, username, passw);
            String req = "DELETE FROM `test` WHERE `ID`=?";
            try(PreparedStatement ps = conn.prepareStatement(req) ){
                ps.setString(1, jTextField2.getText().toString());
                ligne = ps.executeUpdate();
                if(ligne>0){
                    JOptionPane.showMessageDialog(null, "ligne bien supprimé", "bravo", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                       JOptionPane.showMessageDialog(null, "ligne non supprimé", "invalide", JOptionPane.INFORMATION_MESSAGE);

                }
                        
                
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "erreur "+ex.getMessage(), "ERREUR", JOptionPane.WARNING_MESSAGE);
            }
            if(ligne>0){
                DefaultTableModel tb = new DefaultTableModel();
                tb= (DefaultTableModel) jTable3.getModel();
                for(int i =0;i<tb.getRowCount();i++){
                    if(tb.getValueAt(i, 0).toString().equals(jTextField2.getText().toString())){
                        tb.removeRow(i);
                        break;
                    }   
                }
                jTable3.setModel(tb);
            }
            
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "erreur "+e.getMessage(), "ERREUR", JOptionPane.WARNING_MESSAGE);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/bd_excel";
        String username = "root";
        String passw="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url, username, passw);
            String req = "UPDATE `test` SET `nom` = ?, `numero` = ? WHERE `test`.`ID` = ?;";
            try(PreparedStatement ps = conn.prepareStatement(req) ){
                ps.setString(1, jTextField3.getText().toString());
                ps.setString(2, jTextField4.getText().toString());
                ps.setString(3, jTextField2.getText().toString());
                ps.executeUpdate();
                
            } catch (SQLException ex) {
                Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTableModel tb = new DefaultTableModel();
            tb= (DefaultTableModel) jTable3.getModel();
            for(int i =0;i<tb.getRowCount();i++){
               if(tb.getValueAt(i, 0).toString().equals(jTextField2.getText().toString())){
                    tb.setValueAt(jTextField3.getText().toString(), i, 1);
                    tb.setValueAt(jTextField4.getText().toString(), i, 2);
                    break;
                }
            }
            jTable3.setModel(tb);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Ligne bien supprimée", "Bravo!", JOptionPane.WARNING_MESSAGE);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new excel().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(excel.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
